// Those colors are part of w3css: https://www.w3schools.com/w3css/defaulT.asp
export default [
    {"name": "amber", "text": "#000", "background": "#ffc107"},
    {"name": "aqua", "text": "#000", "background": "#00ffff"},
    {"name": "blue", "text": "#fff", "background": "#2196F3"},
    {"name": "light-blue", "text": "#000", "background": "#87CEEB"},
    {"name": "brown", "text": "#fff", "background": "#795548"},
    {"name": "cyan", "text": "#000", "background": "#00bcd4"},
    {"name": "blue-grey", "text": "#fff", "background": "#607d8b"},
    {"name": "green", "text": "#fff", "background": "#4CAF50"},
    {"name": "light-green", "text": "#000", "background": "#8bc34a"},
    {"name": "indigo", "text": "#fff", "background": "#3f51b5"},
    {"name": "khaki", "text": "#000", "background": "#f0e68c"},
    {"name": "lime", "text": "#000", "background": "#cddc39"},
    {"name": "orange", "text": "#000", "background": "#ff9800"},
    {"name": "deep-orange", "text": "#fff", "background": "#ff5722"},
    {"name": "pink", "text": "#fff", "background": "#e91e63"},
    {"name": "purple", "text": "#fff", "background": "#9c27b0"},
    {"name": "deep-purple", "text": "#fff", "background": "#673ab7"},
    {"name": "red", "text": "#fff", "background": "#f44336"},
    {"name": "sand", "text": "#000", "background": "#fdf5e6"},
    {"name": "teal", "text": "#fff", "background": "#009688"},
    {"name": "yellow", "text": "#000", "background": "#ffeb3b"},
    {"name": "white", "text": "#000", "background": "#fff"},
    {"name": "black", "text": "#fff", "background": "#000"},
    {"name": "grey", "text": "#000", "background": "#9e9e9e"},
    {"name": "light-grey", "text": "#000", "background": "#f1f1f1"},
    {"name": "dark-grey", "text": "#fff", "background": "#616161"},
    {"name": "pale-red", "text": "#000", "background": "#ffdddd"},
    {"name": "pale-green", "text": "#000", "background": "#ddffdd"},
    {"name": "pale-yellow", "text": "#000", "background": "#ffffcc"},
    {"name": "pale-blue", "text": "#000", "background": "#ddffff"}
];